[taucorder] typescript client #280 (#281)

diff --git a/.github/workflows/pre-commit.yml b/.github/workflows/pre-commit.yml
--- a/.github/workflows/pre-commit.yml
+++ b/.github/workflows/pre-commit.yml
@@ -88,25 +88,34 @@ jobs:
     - name: Add entry to /etc/hosts
       run: |
         echo "127.0.0.1 hal.computers.com" | sudo tee -a /etc/hosts
-    - name: Build mock server
+    - name: Build mock servers
       run: |
-        cd pkg/spore-drive/clients/mock
-        go build .
+        for project in "spore-drive" "taucorder"; do
+          (
+            cd pkg/$project/clients/mock
+            go build .
+          ) || exit 1
+        done
     - name: Run JS/TS tests with retries
       run: |
         max_attempts=5
-        attempt_num=1
-        cd pkg/spore-drive/clients/js
-        npm i
-        until [ $attempt_num -gt $max_attempts ]
-        do
-          echo "Attempt $attempt_num of $max_attempts"
-          npm run test && break  || echo "Test failed. Retrying..."
-          attempt_num=$((attempt_num + 1))
-          if [ $attempt_num -gt $max_attempts ]
-          then
-            echo "All test attempts failed."
-            exit 1
-          fi
-          sleep 5
+        for project in "pkg/spore-drive/clients/js" "pkg/taucorder/clients/js"; do
+          attempt_num=1 
+          (
+            cd $project
+            echo "Running tests for $project"
+            npm i
+            until [ $attempt_num -gt $max_attempts ]
+            do
+              echo "Attempt $attempt_num of $max_attempts"
+              npm run test && break || echo "Test failed. Retrying..."
+              attempt_num=$((attempt_num + 1))
+              if [ $attempt_num -gt $max_attempts ]
+              then
+                echo "All test attempts failed for $project"
+                exit 1
+              fi
+              sleep 5
+            done
+          ) || exit 1
         done
