fixed web3 tests

diff --git a/.github/workflows/pre-commit.yml b/.github/workflows/pre-commit.yml
--- a/.github/workflows/pre-commit.yml
+++ b/.github/workflows/pre-commit.yml
@@ -55,6 +55,7 @@ jobs:
         do
           echo "Attempt $attempt_num of $max_attempts"
           go test -p 1 ./... && break || echo "Test failed. Retrying..."
+          go test -tags web3 -p 1 ./... && break || echo "Test with web3 tag failed. Retrying..."
           attempt_num=$((attempt_num + 1))
           if [ $attempt_num -gt $max_attempts ]
           then
