run one test at a time - some test use the same ports (to fix later)

diff --git a/.github/workflows/pre-commit.yml b/.github/workflows/pre-commit.yml
--- a/.github/workflows/pre-commit.yml
+++ b/.github/workflows/pre-commit.yml
@@ -54,7 +54,7 @@ jobs:
         until [ $attempt_num -gt $max_attempts ]
         do
           echo "Attempt $attempt_num of $max_attempts"
-          go test ./... && break || echo "Test failed. Retrying..."
+          go test -p 1 ./... && break || echo "Test failed. Retrying..."
           attempt_num=$((attempt_num + 1))
           if [ $attempt_num -gt $max_attempts ]
           then
