added tests to github actions

diff --git a/.github/workflows/pre-commit.yml b/.github/workflows/pre-commit.yml
--- a/.github/workflows/pre-commit.yml
+++ b/.github/workflows/pre-commit.yml
@@ -95,18 +95,24 @@ jobs:
     - name: Run JS/TS tests with retries
       run: |
         max_attempts=5
-        attempt_num=1
-        cd pkg/spore-drive/clients/js
-        npm i
-        until [ $attempt_num -gt $max_attempts ]
-        do
-          echo "Attempt $attempt_num of $max_attempts"
-          npm run test && break  || echo "Test failed. Retrying..."
-          attempt_num=$((attempt_num + 1))
-          if [ $attempt_num -gt $max_attempts ]
-          then
-            echo "All test attempts failed."
-            exit 1
-          fi
-          sleep 5
+        attempt_num=1 
+        for project in "pkg/spore-drive/clients/js" "pkg/taucorder/clients/js"; do
+          attempt_num=1 
+          (
+            cd $project
+            echo "Running tests for $project"
+            npm i
+            until [ $attempt_num -gt $max_attempts ]
+            do
+              echo "Attempt $attempt_num of $max_attempts"
+              npm run test && break || echo "Test failed. Retrying..."
+              attempt_num=$((attempt_num + 1))
+              if [ $attempt_num -gt $max_attempts ]
+              then
+                echo "All test attempts failed for $project"
+                exit 1
+              fi
+              sleep 5
+            done
+          )
         done
