nits

diff --git a/.github/workflows/pre-commit.yml b/.github/workflows/pre-commit.yml
--- a/.github/workflows/pre-commit.yml
+++ b/.github/workflows/pre-commit.yml
@@ -63,3 +63,39 @@ jobs:
           fi
           sleep 5
         done
+    - name: Run Go tests with retries
+      env:
+        TEST_GIT_TOKEN: ${{ secrets.TEST_GIT_TOKEN }}
+      run: |
+        max_attempts=5
+        attempt_num=1
+        until [ $attempt_num -gt $max_attempts ]
+        do
+          echo "Attempt $attempt_num of $max_attempts"
+          go test -p 1 ./... && break || echo "Test failed. Retrying..."
+          attempt_num=$((attempt_num + 1))
+          if [ $attempt_num -gt $max_attempts ]
+          then
+            echo "All test attempts failed."
+            exit 1
+          fi
+          sleep 5
+        done
+    - name: Run JS/TS tests with retries
+      run: |
+        max_attempts=5
+        attempt_num=1
+        cd pkg/spore-drive/clients/js
+        npm i
+        until [ $attempt_num -gt $max_attempts ]
+        do
+          echo "Attempt $attempt_num of $max_attempts"
+          npm run test && break  || echo "Test failed. Retrying..."
+          attempt_num=$((attempt_num + 1))
+          if [ $attempt_num -gt $max_attempts ]
+          then
+            echo "All test attempts failed."
+            exit 1
+          fi
+          sleep 5
+        done
