added test to github action

diff --git a/.github/workflows/pre-commit.yml b/.github/workflows/pre-commit.yml
--- a/.github/workflows/pre-commit.yml
+++ b/.github/workflows/pre-commit.yml
@@ -20,3 +20,43 @@ jobs:
     - uses: actions/checkout@v3
     - uses: actions/setup-python@v3
     - uses: pre-commit/action@v3.0.1
+
+  tests:
+    runs-on: ubuntu-latest
+    needs: pre-commit
+    services:
+      docker:
+        image: docker:19.03.12
+        options: --privileged # required for nested containers
+        ports:
+          - 2375:2375
+        volumes:
+          - /var/lib/docker
+    steps:
+    - name: Set up Docker environment
+      run: |
+        docker info
+    - name: Set up Go
+      uses: actions/setup-go@v4
+      with:
+        go-version: '1.22.0'
+    - name: Checkout code
+      uses: actions/checkout@v3
+    - name: Run Go tests with retries
+      env:
+        TEST_GIT_TOKEN: ${{ secrets.TEST_GIT_TOKEN }}
+      run: |
+        max_attempts=3
+        attempt_num=1
+        until [ $attempt_num -gt $max_attempts ]
+        do
+          echo "Attempt $attempt_num of $max_attempts"
+          go test ./... && break || echo "Test failed. Retrying..."
+          attempt_num=$((attempt_num + 1))
+          if [ $attempt_num -gt $max_attempts ]
+          then
+            echo "All test attempts failed."
+            exit 1
+          fi
+          sleep 5
+        done
